### PR TITLE
fix: show tip on botless frontend

### LINKED ISSUE #202: unrecoverable error on forwarding or save/load
user will try to forward store.xdc to other users, to saved messages or somewhere. or save/load the xdc.

both methods are known to work with other xdc.

however, with the current store.xdc, user will end up in a state where no apps are shown but "update" is offered and "loading...." is shown, all that, of course, will not work.

unrecoverable

to improve the situation, we can show a message if there are no apps at all; _usually_ this state will not happen if used together with a bot as the updates are send directly afterwards.

```
This Webxdc Store
is not connected to a Bot
to get apps from.

To get a working Webxdc Store,
please send "Hi" to
appbot@testrun.org
```

we can make it even _impossible_ to let the message appear when not connected to a bot: for that, we need to send the updates in the same message as the xdc (which might be a good idea anyways, as it avoids error states)

### PR DESCRIPTION
**Pull request by Septias**
This PR adds the initial store state to the store message itself so that the first update is there immediately. It also adds a new message to the uninitialized store to help people get it to work when they just forwarded the store.

Screenshot from 2023-07-30 08-10-19

close #202

### CODE REVIEW

File: frontend/src/index.tsx [hunk 1]
```diff
@@ -236,7 +237,16 @@ const Store: Component = () => {
...
               <Show when={!(lastSerial() === 0)} fallback={
-                <p class="text-center unimportant">Loading store..</p>
+                <div class="text-center unimportant">
+                  <p >This Webxdc Store
+                    is not connected to a Bot
+                    to get apps from.
+                  </p>
+                  <p >To get a working Webxdc Store,
+                    please send "Hi" to
+                    appbot@testrun.org
```
Comment (hpk42) [inline frontend/src/index.tsx:247]: think it needs to say a bit more regarding the e-mail address 
```suggestion
                  <p >To get a working Webxdc store,
                    you need to send "Hi" to a store address and use the store app you get back.  
                    If nothing else you may try sending "Hi" to xstore@testrun.org , an experimental 
                    community deployment offering some curated apps. 
```

**Comment by hpk42** [comment]
could you remove/disable the "update" when you show the hint? 
providing the "update" action does not make sense.

**Comment by r10s** [comment]
how can the screenshot can "Search 5 webxdc apps" and "you're not connected" - i think, these two states are mutual exclusive. 

- either, there are some apps, then they're shown and not the hit
- or there are no apps, then we assume, we're not connected

maybe, this is just a bug in the screenshot :)

anyways, we should hide the "search webxdc apps" in this case, it does not make sense. so that, in case of "not connected error", only the error is shown

**Comment by Septias** [comment]
The screenshot is buggy only on the dev server. Normally there are no apps

**Review by missytake — APPROVED** [review]
works on xstore@testrun.org :)
